gridsome/eslint-plugin-gridsome

lib/rules/require-g-link-to.js

docs: Fix special characters

---

README.md
tools/update-readme/_readme/readme-header.md

closes #16
Add tips about vue-eslint-parser version.
#16

docs: Add tips about vue-eslint-parser version

---

.travis.yml

closes #28
refactoring travis.yml

ci: refacotr travis.yml

---

docs/rules/require-g-link-to.md

docs: reverse correct and incorrect example

---

.gitignore
CONTRIBUTING.md
_hygen/generate/development/eslint.ejs.t
_hygen/generate/development/test.ejs.t
package.json

chore: add development directory

---

package-lock.json
package.json
tests/lib/rules/format-query-block.js
tests/lib/rules/require-g-image-src.js
tests/lib/rules/require-g-link-to.js

- Upgrade ESLInt v6
- Upgrade other packages
- Test follow ESLint v6

build: Upgrade ESLint v6

---

package.json

Upgrages the node engine version from v8 to v10 in package.json
fix #49
Updates the Node engine from v8 to v10
#49

build(node engine): update node engine to v10.13.0

---

.all-contributorsrc
CONTRIBUTING.md
README.md
package-lock.json
package.json

chore: add all-contributors-cli

---

.all-contributorsrc
README.md

docs: add @hacknug as a contributor

---

.github/workflows/test.yml
package.json

re #44 
Use github actions instead of Travis CI.

ci: add github actions workflows

---

.dependabot/config.yml
.github/workflows/test.yml
lib/configs/recommended.js
lib/index.js
lib/rules/format-query-block.js
lib/rules/require-g-image-src.js
lib/rules/require-g-link-to.js
lib/utils/getIndentOptions.js
lib/utils/getPrettierOptions.js
lib/utils/index.js
package-lock.json
package.json

build: upgrade dependencies, add dependabot config

---

README.md

chore: add deploy badge

---

.github/workflows/release.yml
CHANGELOG.md
README.md
package-lock.json
package.json

ci: upgrade checkout

---

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

Ci: fix release

---

package-lock.json
package.json

build: clean dependencies

---

.github/workflows/release.yml

ci: add fetch-depth

---

docs/.vuepress/config.js
package-lock.json
package.json

chore(docs): fix docs build

---

package.json

build: remove test:watch command

---

package.json

Fix lint-staged target file

---

.github/workflows/test.yml

test: remove duplicate test
